### ISSUE TITLE
node_modules folder required to be deployed

### ISSUE THREAD

**Issue by AngeloAvv** [ckeditor/ckeditor4-webpack-template#2]
Hi,
it seems that this setup of ckeditor4 with webpack needs to also deploy the node_modules folder, am I right?

In my deployment cycle I only deploy the dist folder which does not contains the node_modules folder. The only solution seems to copy the ckeditor folder from node_modules into the dist folder and then directly link the library in index.html without passing from webpack.

Does a better solution exists using webpack without deploying the node_modules folder?

These are the errors shown when using without the node_modules folder:
`ckeditor.js:97 GET http://127.0.0.1:8080/node_modules/ckeditor4/config.js?t=J8Q9 net::ERR_ABORTED 404 (Not Found)
append @ ckeditor.js:97
appendTo @ ckeditor.js:73
f @ ckeditor.js:254
load @ ckeditor.js:254
e @ ckeditor.js:254
(anonymous) @ ckeditor.js:254
e @ ckeditor.js:265
o @ ckeditor.js:268
(anonymous) @ ckeditor.js:264
(anonymous) @ ckeditor.js:28
setTimeout (async)
setTimeout @ ckeditor.js:28
e @ ckeditor.js:264
e @ ckeditor.js:344
CKEDITOR.replace @ ckeditor.js:349
(anonymous) @ index.js:5
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ app.js:1
(anonymous) @ universalModuleDefinition:7
(anonymous) @ universalModuleDefinition:1
index.html:1 Refused to apply style from 'http://127.0.0.1:8080/node_modules/ckeditor4/skins/moono-lisa/editor.css?t=J8Q9' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
ckeditor.js:97 GET http://127.0.0.1:8080/node_modules/ckeditor4/lang/it.js?t=J8Q9 net::ERR_ABORTED 404 (Not Found)
append @ ckeditor.js:97
appendTo @ ckeditor.js:73
f @ ckeditor.js:254
load @ ckeditor.js:254
load @ ckeditor.js:251
(anonymous) @ ckeditor.js:268
(anonymous) @ ckeditor.js:268
n @ ckeditor.js:514
loadPart @ ckeditor.js:516
(anonymous) @ ckeditor.js:268
(anonymous) @ ckeditor.js:268
r @ ckeditor.js:10
(anonymous) @ ckeditor.js:11
CKEDITOR.editor.CKEDITOR.editor.fire @ ckeditor.js:13
fireOnce @ ckeditor.js:12
CKEDITOR.editor.CKEDITOR.editor.fireOnce @ ckeditor.js:13
e @ ckeditor.js:265
(anonymous) @ ckeditor.js:266
callback @ ckeditor.js:254
d @ ckeditor.js:252
u @ ckeditor.js:253
h @ ckeditor.js:253
CKEDITOR.env.ie.a.$.onerror @ ckeditor.js:254
error (async)
f @ ckeditor.js:254
load @ ckeditor.js:254
e @ ckeditor.js:254
(anonymous) @ ckeditor.js:254
e @ ckeditor.js:265
o @ ckeditor.js:268
(anonymous) @ ckeditor.js:264
(anonymous) @ ckeditor.js:28
setTimeout (async)
setTimeout @ ckeditor.js:28
e @ ckeditor.js:264
e @ ckeditor.js:344
CKEDITOR.replace @ ckeditor.js:349
(anonymous) @ index.js:5
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ app.js:1
(anonymous) @ universalModuleDefinition:7
(anonymous) @ universalModuleDefinition:1
ckeditor.js:251 Uncaught TypeError: Cannot set property 'dir' of undefined
    at Object.t (ckeditor.js:251)
    at d (ckeditor.js:252)
    at Array.u (ckeditor.js:253)
    at h (ckeditor.js:253)
    at HTMLScriptElement.CKEDITOR.env.ie.a.$.onerror (ckeditor.js:254)`

**Comment by Comandeer** [comment]
Sorry for the very delayed response.

Yes, currently `/node_modules/ckeditor4`\` has to be deployed alongside the `dist` directory.

However there is a simple workaround:

1.  Change path in `src/ckeditor/basePath.js` to `/ckeditor4/` or `./ckeditor4/`.
2.  Copy `node_modules/ckeditor4` directory to `dist` after running webpack.

I'll implement this workaround directly to the repo.

**Comment by f1ames** [comment]
@AngeloAvv, @KyeRussell - the change mentioned in https://github.com/ckeditor/ckeditor4-webpack-template/issues/2#issuecomment-640616579 landed on `master`. Now all CKEditor 4 files are copied automatically to `dist/` directory.
